---
# This role installs httpd and git

- name: Installs packages
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - git
    # Fixes issues with git
    - curl
 
- name: Start http service
  service: 
    name: httpd
    state: started
    enabled: yes