---
# Provision instances in AWS
- name: Provision instances in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Launch webserver instances
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      volumes:
         - device_name: /dev/sda1
           volume_size: 10
           delete_on_termination: true
      region: "{{ ec2_region }}"
      instance_tags: "{'ansible_group':'web', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
      count: "{{ ec2_instance_count }}"
      wait: true
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
